### ISSUE TITLE
Add a license please

### ISSUE THREAD

**Issue by manodeep** [ellawang44/image_manip#1]
The repo does not have any license which restricts anyone from even looking at the code (though the AI training companies will probably steal the code anyway)

**Comment by ellawang44** [comment]
Sure, I've added a license. This is only a fun side project, and very little code. I'm not very worried about people distributing or using this code.

**Comment by ellawang44** [comment]
closing

**Comment by ellawang44** [comment]
resolved

**Comment by manodeep** [comment]
Thank you 🙂
